### ISSUE TITLE
Confusing spec comments

### ISSUE THREAD

**Issue by itzsaga** [learn-co-curriculum/activerecord-tvland#13]
The spec comments create confusion. Some of the things marked TODO are already done.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#18.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @itzsaga,

Thank you for spotting this and providing feedback. The comments have been removed from the specs in this lab, so this issue should be resolved.

Thank you for contributing to a Learn lesson!
