### ISSUE TITLE
Incorrect instruction

### ISSUE THREAD

**Issue by sarjumulmi** [learn-co-curriculum/activerecord-tvland#15]
Instructions call for show with a name and a genre, and character with a name and a show_id––a character will belong to a show.

Specs have show with name, season and day; character has name, show_id and actor_id.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#18.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @sarjumulmi,

Thank you for opening this issue. This lesson's instructions have been updated to correctly align with what is being expected in the tests, and believe this issue is resolved.

Thank you for contributing to a Learn lesson!
