### ISSUE TITLE
Excellent Lesson

### ISSUE THREAD

**Issue by Ary770** [learn-co-curriculum/activerecord-tvland#16]
Just want to give my feedback about the lesson. Thought it was really great. Crystal clear. Avi is an amazing teacher and the way he explained the concepts really resonated with me. I think it's the perfect place for this video. I appreciate more the lessons and they "sink in" even more once I've gone through a couple of labs myself and have actually tested the waters. Especially since Avi goes a bit quick. Really enjoyed the lesson and answered lingering question I had.

**Comment by curiositypaths** [comment]
Hi there,

We are super glad you found the lesson useful.
