### ISSUE TITLE
The README is missing a few instructions.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/activerecord-tvland#20]
Hello. I noticed a couple of things that were missing (or inaccurate) in the README. 

First of all, the README's description of the "list_roles" method is a little misleading. It says that this method "lists all of the characters that actor has". That led me to think that I was supposed to have the method return an array of characters, or else their names. However, this is not the case; the test for that method requires you to list each character's name ALONG WITH the name of the show that the character is in.

The other issue I found is that while the README mentions the associations between the actors, characters, and shows, it does NOT mention these important associations: that a network has many shows and that a show belongs to a network. Both associations are needed to pass the tests (the first association having already been coded for us).

As always, thanks for looking into this!

Sdcrouse

**Comment by Sdcrouse** [comment]
One more thing that I would like to add to this: the README mentions that a show has many actors through characters, but there is no test for that.

**Comment by maxwellbenton** [comment]
Hey @Sdcrouse,

Thank you for opening this issue! We've updated this lesson's instructions and some of the tests using your feedback. Specifically - clarifying the expectations for `list_roles` and the specific associations that will need to be established that were previously missing, as well as adding an additional method and test to check for the has many through relationship of shows and actors.

As always, thank you for your contributions to this Learn lesson!
