### ISSUE TITLE
"Migrator.migrate" should be "Migration.migrate"

### ISSUE THREAD

**Issue by geluso** [learn-co-curriculum/activerecord-tvland#21]
From a student:

Hey everyone, there seems to be a typo on the ‘ActiveRecord Associations Lab II’ Rakefile. Row 10 has `ActiveRecord::Migrator.migrate("db/migrate/")` , but it should be  `ActiveRecord::Migration.migrate("db/migrate/")`

**Comment by maxwellbenton** [comment]
Hi @geluso,

Thanks for reporting this. I've made the change tested it out and updated master/solution with this fix.
