### ISSUE TITLE
any way to reset a lab on Learn IDE?

### ISSUE THREAD

**Issue by CalebKnox** [learn-co-curriculum/activerecord-tvland#9]
I was having trouble with this lab since none of my added migrations would run. After trying a few things, it was suggested that I delete my repository so that I could get a fresh start on the lab (perhaps that would fix my issue). I did so, but now I can't get the full lab to appear in my Learn IDE (probably since I deleted the files on the IDE as well as in the repository). Currently, I have  activerecord-tvland-v-000 in my command line, but I don't have any visual representation on the file tree on the left. Thank you.

**Comment by AnnJohn** [comment]
hi @CalebKnox sorry for the delay with this. Since this is a question related to the Learn IDE can you email support+ide@learn.co and someone should be able to help you out. Thanks!
